name: Publicar Site Isotelha
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Baixando o código do GitHub
        uses: actions/checkout@v3

      - name: Enviando para a HostGator via FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.SERVIDOR_FTP }}
          username: ${{ secrets.USUARIO_FTP }}
          password: ${{ secrets.FTP_SENHA }}
          local-dir: ./dist/
          server-dir: ./
